from uuid import UUID
from typing import List, Dict, Any, Callable, Awaitable
from src.domains.data_ingestion.repositories.import_record import ImportRecordRepository
from src.domains.data_ingestion.repositories.import_job import ImportJobRepository
from src.domains.data_ingestion.services.import_summary import ImportSummaryService
from src.foundation.exceptions.base import ValidationException

from src.domains.operations.schemas.sales_order import SalesOrderCreate
from src.domains.operations.schemas.tax_invoice import TaxInvoiceCreate
from src.domains.operations.schemas.payment import PaymentCreate
from src.domains.operations.schemas.settlement import SettlementCreate
# RefundCreate can be added if needed, but not generated by adapters yet

class CommitService:
    def __init__(
        self, 
        record_repository: ImportRecordRepository,
        job_repository: ImportJobRepository,
        summary_service: ImportSummaryService,
        sales_order_service: Any,
        tax_invoice_service: Any,
        payment_service: Any,
        settlement_service: Any
    ):
        self.record_repository = record_repository
        self.job_repository = job_repository
        self.summary_service = summary_service
        
        self.sales_order_service = sales_order_service
        self.tax_invoice_service = tax_invoice_service
        self.payment_service = payment_service
        self.settlement_service = settlement_service
        
        # Dispatcher strategies
        self.strategies: Dict[str, Callable[[Dict[str, Any], UUID], Awaitable[Any]]] = {
            "SALES_ORDER": self._commit_sales_order,
            "TAX_INVOICE": self._commit_tax_invoice,
            "PAYMENT": self._commit_payment,
            "SETTLEMENT": self._commit_settlement
        }

    async def _commit_sales_order(self, normalized_data: Dict[str, Any], user_id: UUID) -> Any:
        schema = SalesOrderCreate(**normalized_data)
        return await self.sales_order_service.process_commit(schema, user_id)

    async def _commit_tax_invoice(self, normalized_data: Dict[str, Any], user_id: UUID) -> Any:
        schema = TaxInvoiceCreate(**normalized_data)
        return await self.tax_invoice_service.process_commit(schema, user_id)

    async def _commit_payment(self, normalized_data: Dict[str, Any], user_id: UUID) -> Any:
        schema = PaymentCreate(**normalized_data)
        return await self.payment_service.process_commit(schema, user_id)

    async def _commit_settlement(self, normalized_data: Dict[str, Any], user_id: UUID) -> Any:
        schema = SettlementCreate(**normalized_data)
        return await self.settlement_service.process_commit(schema, user_id)

    async def approve_job_records(self, job_id: UUID, updated_by: UUID) -> None:
        """
        Transitions all VALID records for a job to APPROVED status.
        """
        job = await self.job_repository.get_by_id(job_id)
        if not job:
            raise ValidationException(message="Job not found")
            
        valid_records = await self.record_repository.get_by_status(job_id, status="VALID", skip=0, limit=10000)
        for record in valid_records:
            record.status = "APPROVED"
            record.updated_by = updated_by
            await self.record_repository.update(record)
            
        job.status = "APPROVED"
        await self.job_repository.update(job)

    async def commit_job_records(self, job_id: UUID, updated_by: UUID) -> None:
        """
        Retrieves all APPROVED records for a job and dispatches them to their commit strategy.
        """
        job = await self.job_repository.get_by_id(job_id)
        if not job:
            raise ValidationException(message="Job not found")
            
        if job.status != "APPROVED":
            raise ValidationException(message="Job must be APPROVED before committing")
            
        job.status = "COMMITTING"
        await self.job_repository.update(job)
            
        approved_records = await self.record_repository.get_by_status(job_id, status="APPROVED", skip=0, limit=10000)
        
        success_count = 0
        failure_count = 0
        
        for record in approved_records:
            try:
                strategy = self.strategies.get(record.record_type)
                if not strategy:
                    raise ValueError(f"No commit strategy found for {record.record_type}")
                
                await strategy(record.normalized_data, updated_by)
                
                record.status = "COMMITTED"
                record.updated_by = updated_by
                await self.record_repository.update(record)
                success_count += 1
            except Exception as e:
                import logging
                logging.error(f"Failed to commit record {record.id} of type {record.record_type}: {str(e)}")
                record.status = "FAILED_COMMIT"
                record.updated_by = updated_by
                await self.record_repository.update(record)
                failure_count += 1
                
        if failure_count == 0:
            job.status = "COMMITTED"
        else:
            job.status = "PARTIALLY_COMMITTED"
        await self.job_repository.update(job)
