"""add job work models

Revision ID: 0d33205fbc6c
Revises: e67afde9fc2e
Create Date: 2026-08-10 11:35:09.245573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d33205fbc6c'
down_revision: Union[str, None] = 'e67afde9fc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_job_work_orders',
    sa.Column('jwo_number', sa.String(length=255), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('target_item_id', sa.Uuid(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['target_item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_orders_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_orders_jwo_number'), ['jwo_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_orders_target_item_id'), ['target_item_id'], unique=False)

    op.create_table('inventory_job_work_issues',
    sa.Column('issue_number', sa.String(length=255), nullable=False),
    sa.Column('jwo_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['jwo_id'], ['inventory_job_work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_issue_number'), ['issue_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_jwo_id'), ['jwo_id'], unique=False)

    op.create_table('inventory_job_work_receipts',
    sa.Column('receipt_number', sa.String(length=255), nullable=False),
    sa.Column('jwo_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('scrap_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['jwo_id'], ['inventory_job_work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_jwo_id'), ['jwo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_receipt_number'), ['receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_jwo_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_item_id'))

    op.drop_table('inventory_job_work_receipts')
    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_jwo_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_issue_number'))

    op.drop_table('inventory_job_work_issues')
    with op.batch_alter_table('inventory_job_work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_orders_target_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_orders_jwo_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_orders_job_worker_id'))

    op.drop_table('inventory_job_work_orders')
    # ### end Alembic commands ###
