"""add parent_id to categories

Revision ID: 33cbb6bbc061
Revises: e06b777bd136
Create Date: 2026-08-07 12:48:33.616933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cbb6bbc061'
down_revision: Union[str, None] = 'e06b777bd136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('item_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FINISHED_GOODS', 'RAW_MATERIAL', 'CONSUMABLE', 'PACKAGING_MATERIAL', 'ASSET', name='item_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'FINISHED_GOODS'"))
        batch_op.create_foreign_key('fk_categories_parent_id', 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FINISHED_GOODS', 'RAW_MATERIAL', 'CONSUMABLE', 'PACKAGING_MATERIAL', 'ASSET', name='item_type_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'FINISHED_GOODS'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=sa.Enum('FINISHED_GOODS', 'RAW_MATERIAL', 'CONSUMABLE', 'PACKAGING_MATERIAL', 'ASSET', name='item_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'FINISHED_GOODS'"))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_parent_id', type_='foreignkey')
        batch_op.alter_column('item_type',
               existing_type=sa.Enum('FINISHED_GOODS', 'RAW_MATERIAL', 'CONSUMABLE', 'PACKAGING_MATERIAL', 'ASSET', name='item_type_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'FINISHED_GOODS'"))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
