"""Add shopdeck_sku_id to SKUModel

Revision ID: 4118e8621401
Revises: 7a063e8626db
Create Date: 2026-08-18 22:01:08.017260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4118e8621401'
down_revision: Union[str, None] = '7a063e8626db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_audit_logs',
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('executed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rollback_status', sa.String(length=50), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_audit_logs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_audit_logs_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopdeck_sku_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_skus_shopdeck_sku_id'), ['shopdeck_sku_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skus_shopdeck_sku_id'))
        batch_op.drop_column('shopdeck_sku_id')

    with op.batch_alter_table('import_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_import_audit_logs_batch_id'))

    op.drop_table('import_audit_logs')
    # ### end Alembic commands ###
