"""Inventory Transformation Engine

Revision ID: 481a3e15d102
Revises: 0d33205fbc6c
Create Date: 2026-08-11 12:41:21.496716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481a3e15d102'
down_revision: Union[str, None] = '0d33205fbc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transformation_register',
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('destination_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('quantity_produced', sa.Integer(), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=True),
    sa.Column('reference_document', sa.String(length=255), nullable=False),
    sa.Column('transformation_reason', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['destination_item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transformation_register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_destination_item_id'), ['destination_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_reference_document'), ['reference_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_source_item_id'), ['source_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_transformation_reason'), ['transformation_reason'], unique=False)

    op.create_table('masters_boms',
    sa.Column('bom_number', sa.String(length=255), nullable=False),
    sa.Column('target_item_id', sa.Uuid(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('masters_boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masters_boms_bom_number'), ['bom_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_masters_boms_target_item_id'), ['target_item_id'], unique=False)

    op.create_table('inventory_job_worker_stock',
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('issued_quantity', sa.Integer(), nullable=False),
    sa.Column('consumed_quantity', sa.Integer(), nullable=False),
    sa.Column('pending_quantity', sa.Integer(), nullable=False),
    sa.Column('last_movement_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['last_movement_id'], ['inventory_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_worker_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_worker_stock_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_worker_stock_job_worker_id'), ['job_worker_id'], unique=False)

    op.create_table('masters_bom_items',
    sa.Column('bom_id', sa.Uuid(), nullable=False),
    sa.Column('component_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['masters_boms.id'], ),
    sa.ForeignKeyConstraint(['component_item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masters_bom_items_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_masters_bom_items_component_item_id'), ['component_item_id'], unique=False)

    with op.batch_alter_table('inventory_goods_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_type', sa.String(length=50), nullable=False, server_default='RAW_MATERIAL_RECEIPT'))

    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_worker_id', sa.Uuid(), nullable=False))
        batch_op.drop_index('ix_inventory_job_work_issues_jwo_id')
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'), ['job_worker_id'], unique=False)
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, 'masters_suppliers', ['job_worker_id'], ['id'])
        batch_op.drop_column('jwo_id')

    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_worker_id', sa.Uuid(), nullable=False))
        batch_op.drop_index('ix_inventory_job_work_receipts_jwo_id')
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'), ['job_worker_id'], unique=False)
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, 'masters_suppliers', ['job_worker_id'], ['id'])
        batch_op.drop_column('jwo_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwo_id', sa.CHAR(length=32), nullable=False))
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, 'inventory_job_work_orders', ['jwo_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'))
        batch_op.create_index('ix_inventory_job_work_receipts_jwo_id', ['jwo_id'], unique=False)
        batch_op.drop_column('job_worker_id')

    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwo_id', sa.CHAR(length=32), nullable=False))
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, 'inventory_job_work_orders', ['jwo_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'))
        batch_op.create_index('ix_inventory_job_work_issues_jwo_id', ['jwo_id'], unique=False)
        batch_op.drop_column('job_worker_id')

    with op.batch_alter_table('inventory_goods_receipts', schema=None) as batch_op:
        batch_op.drop_column('receipt_type')

    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masters_bom_items_component_item_id'))
        batch_op.drop_index(batch_op.f('ix_masters_bom_items_bom_id'))

    op.drop_table('masters_bom_items')
    with op.batch_alter_table('inventory_job_worker_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_worker_stock_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_worker_stock_item_id'))

    op.drop_table('inventory_job_worker_stock')
    with op.batch_alter_table('masters_boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masters_boms_target_item_id'))
        batch_op.drop_index(batch_op.f('ix_masters_boms_bom_number'))

    op.drop_table('masters_boms')
    with op.batch_alter_table('inventory_transformation_register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_transformation_reason'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_source_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_reference_document'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_destination_item_id'))

    op.drop_table('inventory_transformation_register')
    # ### end Alembic commands ###
