"""Add BOM v2 features

Revision ID: 5593efb16e36
Revises: 481a3e15d102
Create Date: 2026-08-11 14:47:40.812540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5593efb16e36'
down_revision: Union[str, None] = '481a3e15d102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Unrelated tables removed from migration

    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tolerance_percentage', sa.Numeric(precision=5, scale=2), nullable=False))

    with op.batch_alter_table('masters_boms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('effective_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('effective_to', sa.Date(), nullable=True))
        batch_op.drop_index('ix_masters_boms_bom_number')
        batch_op.create_index(batch_op.f('ix_masters_boms_bom_number'), ['bom_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters_boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masters_boms_bom_number'))
        batch_op.create_index('ix_masters_boms_bom_number', ['bom_number'], unique=1)
        batch_op.drop_column('effective_to')
        batch_op.drop_column('effective_from')
        batch_op.drop_column('version')

    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.drop_column('tolerance_percentage')
        batch_op.drop_column('wastage_percentage')

    # Unrelated tables removed from downgrade

    # ### end Alembic commands ###
