"""add_missing_domain_tables

Revision ID: 739e05f6d81f
Revises: f161b6403fe1
Create Date: 2026-08-29 02:14:46.804464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '739e05f6d81f'
down_revision: Union[str, None] = 'f161b6403fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_journal_entries',
    sa.Column('journal_number', sa.String(length=255), nullable=False),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('narration', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_journal_entries_journal_number'), ['journal_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounting_journal_entries_reference_id'), ['reference_id'], unique=False)

    op.create_table('accounting_ledgers',
    sa.Column('ledger_code', sa.String(length=100), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_ledgers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_ledgers_ledger_code'), ['ledger_code'], unique=True)

    op.create_table('categories',
    sa.Column('category_code', sa.String(length=50), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('item_type', sa.Enum('FINISHED_GOODS', 'RAW_MATERIAL', 'CONSUMABLE', 'PACKAGING_MATERIAL', 'ASSET', name='item_type_enum'), server_default='FINISHED_GOODS', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_category_code'), ['category_code'], unique=True)

    op.create_table('companies',
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('pan')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_code'), ['company_code'], unique=True)

    op.create_table('import_audit_logs',
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('executed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rollback_status', sa.String(length=50), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_audit_logs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('integrations',
    sa.Column('integration_code', sa.String(length=50), nullable=False),
    sa.Column('integration_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_integration_code'), ['integration_code'], unique=True)

    op.create_table('inventory_outbound_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_outbound_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_outbound_events_event_id'), ['event_id'], unique=True)

    op.create_table('masters_suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_job_worker', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matching_jobs',
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orders_processed', sa.Integer(), nullable=False),
    sa.Column('payments_processed', sa.Integer(), nullable=False),
    sa.Column('settlements_processed', sa.Integer(), nullable=False),
    sa.Column('invoices_processed', sa.Integer(), nullable=False),
    sa.Column('successful_matches', sa.Integer(), nullable=False),
    sa.Column('failed_matches', sa.Integer(), nullable=False),
    sa.Column('exceptions_generated', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations_return_policies',
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('return_window_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_from')
    )
    op.create_table('operations_settlements',
    sa.Column('settlement_id', sa.String(length=255), nullable=False),
    sa.Column('cycle_date', sa.String(length=255), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('utr_number', sa.String(length=255), nullable=False),
    sa.Column('bank_account', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_settlements_settlement_id'), ['settlement_id'], unique=True)

    op.create_table('packer_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packer_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packer_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_packer_events_order_id'), ['order_id'], unique=False)

    op.create_table('product_attributes',
    sa.Column('attribute_code', sa.String(length=50), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attribute_name')
    )
    with op.batch_alter_table('product_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_attributes_attribute_code'), ['attribute_code'], unique=True)

    op.create_table('shopdeck_downloaded_reports',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sync_run_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopdeck_downloaded_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopdeck_downloaded_reports_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopdeck_downloaded_reports_sync_run_id'), ['sync_run_id'], unique=False)

    op.create_table('system_sequences',
    sa.Column('sequence_name', sa.String(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_sequences_sequence_name'), ['sequence_name'], unique=True)

    op.create_table('units_of_measure',
    sa.Column('unit_code', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('unit_type', sa.String(length=20), server_default='INTEGER', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name'),
    sa.UniqueConstraint('unit_name')
    )
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_of_measure_unit_code'), ['unit_code'], unique=True)

    op.create_table('warehouses',
    sa.Column('warehouse_code', sa.String(length=50), nullable=False),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.String(length=20), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_name')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_warehouse_code'), ['warehouse_code'], unique=True)

    op.create_table('accounting_journal_lines',
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_id', sa.Uuid(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('narration', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['accounting_journal_entries.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['accounting_ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_journal_lines_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_journal_lines_ledger_id'), ['ledger_id'], unique=False)

    op.create_table('category_attributes',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('attribute_id', sa.Uuid(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', 'attribute_id', 'id')
    )
    op.create_table('import_jobs',
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_integration_id'), ['integration_id'], unique=False)

    op.create_table('inventory_goods_receipts',
    sa.Column('grn_number', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_type', sa.String(length=50), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('challan_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grn_number')
    )
    op.create_table('inventory_purchase_returns',
    sa.Column('return_number', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reference_grn', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_table('jwa_job_worker_payments',
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_account', sa.String(length=255), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwa_job_worker_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwa_job_worker_payments_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwa_job_worker_payments_reference'), ['reference'], unique=True)

    op.create_table('matching_exceptions',
    sa.Column('match_job_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['match_job_id'], ['matching_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matching_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_exceptions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_exceptions_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_exceptions_match_job_id'), ['match_job_id'], unique=False)

    op.create_table('matching_relationships',
    sa.Column('match_job_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['match_job_id'], ['matching_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', 'relationship_type', name='uq_match_relationship')
    )
    with op.batch_alter_table('matching_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_relationships_match_job_id'), ['match_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_relationships_relationship_type'), ['relationship_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_relationships_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_relationships_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_relationships_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matching_relationships_target_type'), ['target_type'], unique=False)

    op.create_table('operations_sales_orders',
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_mobile', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.String(length=1000), nullable=False),
    sa.Column('shipping_pincode', sa.String(length=20), nullable=False),
    sa.Column('shipping_city', sa.String(length=100), nullable=False),
    sa.Column('shipping_state', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cod_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('terminal_date', sa.Date(), nullable=True),
    sa.Column('return_policy_id', sa.Uuid(), nullable=True),
    sa.Column('return_window_days_at_delivery', sa.Integer(), nullable=True),
    sa.Column('return_watch_until', sa.Date(), nullable=True),
    sa.Column('return_created_date', sa.Date(), nullable=True),
    sa.Column('return_delivered_date', sa.Date(), nullable=True),
    sa.Column('has_open_rto_expectation', sa.Boolean(), nullable=False),
    sa.Column('has_open_return_expectation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['return_policy_id'], ['operations_return_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_sales_orders_external_order_id'), ['external_order_id'], unique=False)

    op.create_table('products',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('item_type', sa.Enum('FINISHED_GOODS', 'RAW_MATERIAL', 'CONSUMABLE', 'PACKAGING_MATERIAL', 'ASSET', name='item_type_enum'), server_default='FINISHED_GOODS', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_product_code'), ['product_code'], unique=True)

    op.create_table('import_files',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_job_id')
    )
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_files_md5_hash'), ['md5_hash'], unique=False)

    op.create_table('import_records',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalized_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_records_import_job_id'), ['import_job_id'], unique=False)

    op.create_table('import_summaries',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('successful_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_job_id')
    )
    op.create_table('operations_order_state_transitions',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('old_status', sa.String(length=100), nullable=True),
    sa.Column('new_status', sa.String(length=100), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('transition_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['operations_sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_order_id', 'new_status', 'observed_at', name='uix_order_transition_idempotency')
    )
    with op.batch_alter_table('operations_order_state_transitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_order_state_transitions_order_id'), ['order_id'], unique=False)

    op.create_table('operations_payments',
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('order_reference', sa.String(length=255), nullable=False),
    sa.Column('matched_order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gateway_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gateway_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('external_settlement_id', sa.String(length=255), nullable=True),
    sa.Column('utr_number', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['matched_order_id'], ['operations_sales_orders.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['operations_settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_payments_matched_order_id'), ['matched_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_payments_order_reference'), ['order_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_payments_settlement_id'), ['settlement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_payments_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('operations_refunds',
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('order_reference', sa.String(length=255), nullable=False),
    sa.Column('matched_order_id', sa.Uuid(), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gateway_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('refund_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settlement_id', sa.Uuid(), nullable=True),
    sa.Column('external_settlement_id', sa.String(length=255), nullable=True),
    sa.Column('utr_number', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['matched_order_id'], ['operations_sales_orders.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['operations_settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_refunds_order_reference'), ['order_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_refunds_settlement_id'), ['settlement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_refunds_transaction_id'), ['transaction_id'], unique=True)

    op.create_table('operations_tax_invoices',
    sa.Column('invoice_no', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('customer_state', sa.String(length=100), nullable=False),
    sa.Column('total_base_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['operations_sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_tax_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_tax_invoices_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_tax_invoices_order_id'), ['order_id'], unique=False)

    op.create_table('product_attributes_link',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_attribute_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_attribute_id'], ['product_attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'product_attribute_id')
    )
    op.create_table('skus',
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('sku_code', sa.String(length=50), nullable=True),
    sa.Column('shopdeck_sku_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=500), nullable=True),
    sa.Column('pattern', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('thread_count', sa.String(length=50), nullable=True),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('attribute_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skus_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_skus_shopdeck_sku_id'), ['shopdeck_sku_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_skus_sku_code'), ['sku_code'], unique=True)

    op.create_table('import_errors',
    sa.Column('import_job_id', sa.Uuid(), nullable=False),
    sa.Column('import_record_id', sa.Uuid(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.ForeignKeyConstraint(['import_record_id'], ['import_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_errors_import_job_id'), ['import_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_errors_import_record_id'), ['import_record_id'], unique=False)

    op.create_table('inventory_balances',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_reasons', sa.JSON(), nullable=False),
    sa.Column('last_movement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'sku_id', name='uq_inventory_balance_warehouse_sku')
    )
    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_balances_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_balances_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inventory_exceptions',
    sa.Column('exception_number', sa.String(length=255), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('exception_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_exceptions_exception_number'), ['exception_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_exceptions_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_exceptions_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inventory_goods_receipt_items',
    sa.Column('grn_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['inventory_goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_job_work_issues',
    sa.Column('issue_reference', sa.String(length=255), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('issued_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('pending_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_issue_reference'), ['issue_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'), ['job_worker_id'], unique=False)

    op.create_table('inventory_job_work_receipts',
    sa.Column('receipt_number', sa.String(length=255), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('scrap_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_receipt_number'), ['receipt_number'], unique=True)

    op.create_table('inventory_job_work_returns',
    sa.Column('return_number', sa.String(length=255), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_returns_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_returns_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_returns_return_number'), ['return_number'], unique=True)

    op.create_table('inventory_movements',
    sa.Column('movement_number', sa.String(length=255), nullable=False),
    sa.Column('movement_type', sa.String(length=100), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_number'), ['movement_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_movements_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('inventory_purchase_return_items',
    sa.Column('return_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['inventory_purchase_returns.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jwa_job_work_rates',
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate_basis', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwa_job_work_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwa_job_work_rates_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwa_job_work_rates_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index('uix_active_job_work_rate', ['job_worker_id', 'sku_id'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = true'))

    op.create_table('masters_boms',
    sa.Column('bom_number', sa.String(length=255), nullable=False),
    sa.Column('bom_name', sa.String(length=255), nullable=True),
    sa.Column('target_item_id', sa.Uuid(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['target_item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('masters_boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masters_boms_bom_number'), ['bom_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_masters_boms_target_item_id'), ['target_item_id'], unique=False)

    op.create_table('operations_sales_order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('external_sku_code', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['operations_sales_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_sales_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_sales_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('operations_tax_invoice_items',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('sku_id', sa.Uuid(), nullable=True),
    sa.Column('external_sku_code', sa.String(length=255), nullable=False),
    sa.Column('hsn_code', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['operations_tax_invoices.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations_tax_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_tax_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('packaging',
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('breadth', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('package_contents', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id')
    )
    op.create_table('pricing',
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id')
    )
    op.create_table('product_images',
    sa.Column('sku_id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_sku_id'), ['sku_id'], unique=False)

    op.create_table('inventory_job_work_allocations',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['inventory_job_work_issues.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['inventory_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_work_allocations_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_work_allocations_movement_id'), ['movement_id'], unique=False)

    op.create_table('inventory_job_worker_stock',
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('issued_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('pending_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('last_movement_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['last_movement_id'], ['inventory_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_worker_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_job_worker_stock_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_job_worker_stock_job_worker_id'), ['job_worker_id'], unique=False)

    op.create_table('inventory_transformation_register',
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('destination_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_consumed', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('source_uom_id', sa.Uuid(), nullable=True),
    sa.Column('destination_uom_id', sa.Uuid(), nullable=True),
    sa.Column('bom_id', sa.Uuid(), nullable=True),
    sa.Column('bom_quantity_per_unit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('job_worker_id', sa.Uuid(), nullable=True),
    sa.Column('reference_document', sa.String(length=255), nullable=False),
    sa.Column('transformation_reason', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['masters_boms.id'], ),
    sa.ForeignKeyConstraint(['destination_item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['destination_uom_id'], ['units_of_measure.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['source_uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_transformation_register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_destination_item_id'), ['destination_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_destination_uom_id'), ['destination_uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_reference_document'), ['reference_document'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_source_item_id'), ['source_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_source_uom_id'), ['source_uom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_transformation_register_transformation_reason'), ['transformation_reason'], unique=False)

    op.create_table('jwa_job_work_expenses',
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('job_worker_id', sa.Uuid(), nullable=False),
    sa.Column('finished_product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('rate_basis', sa.String(length=50), nullable=False),
    sa.Column('rate_version_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('source_receipt_number', sa.String(length=255), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['finished_product_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['rate_version_id'], ['jwa_job_work_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwa_job_work_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwa_job_work_expenses_finished_product_id'), ['finished_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwa_job_work_expenses_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwa_job_work_expenses_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_jwa_job_work_expenses_source_receipt_id'), ['source_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwa_job_work_expenses_source_receipt_number'), ['source_receipt_number'], unique=False)

    op.create_table('masters_bom_items',
    sa.Column('bom_id', sa.Uuid(), nullable=False),
    sa.Column('component_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('uom_id', sa.Uuid(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('wastage_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tolerance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['masters_boms.id'], ),
    sa.ForeignKeyConstraint(['component_item_id'], ['skus.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_masters_bom_items_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_masters_bom_items_component_item_id'), ['component_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_masters_bom_items_uom_id'), ['uom_id'], unique=False)

    op.create_table('jwa_payable_allocations',
    sa.Column('expense_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['jwa_job_work_expenses.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['jwa_job_worker_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwa_payable_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwa_payable_allocations_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jwa_payable_allocations_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jwa_payable_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwa_payable_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_jwa_payable_allocations_expense_id'))

    op.drop_table('jwa_payable_allocations')
    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masters_bom_items_uom_id'))
        batch_op.drop_index(batch_op.f('ix_masters_bom_items_component_item_id'))
        batch_op.drop_index(batch_op.f('ix_masters_bom_items_bom_id'))

    op.drop_table('masters_bom_items')
    with op.batch_alter_table('jwa_job_work_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_expenses_source_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_expenses_source_receipt_id'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_expenses_reference'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_expenses_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_expenses_finished_product_id'))

    op.drop_table('jwa_job_work_expenses')
    with op.batch_alter_table('inventory_transformation_register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_transformation_reason'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_source_uom_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_source_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_reference_document'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_destination_uom_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_destination_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_transformation_register_bom_id'))

    op.drop_table('inventory_transformation_register')
    with op.batch_alter_table('inventory_job_worker_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_worker_stock_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_worker_stock_item_id'))

    op.drop_table('inventory_job_worker_stock')
    with op.batch_alter_table('inventory_job_work_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_allocations_movement_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_allocations_issue_id'))

    op.drop_table('inventory_job_work_allocations')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_sku_id'))

    op.drop_table('product_images')
    op.drop_table('pricing')
    op.drop_table('packaging')
    with op.batch_alter_table('operations_tax_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_tax_invoice_items_invoice_id'))

    op.drop_table('operations_tax_invoice_items')
    with op.batch_alter_table('operations_sales_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_sales_order_items_order_id'))

    op.drop_table('operations_sales_order_items')
    with op.batch_alter_table('masters_boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_masters_boms_target_item_id'))
        batch_op.drop_index(batch_op.f('ix_masters_boms_bom_number'))

    op.drop_table('masters_boms')
    with op.batch_alter_table('jwa_job_work_rates', schema=None) as batch_op:
        batch_op.drop_index('uix_active_job_work_rate', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = true'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_rates_sku_id'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_work_rates_job_worker_id'))

    op.drop_table('jwa_job_work_rates')
    op.drop_table('inventory_purchase_return_items')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_sku_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_reference_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_number'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('inventory_job_work_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_returns_return_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_returns_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_returns_item_id'))

    op.drop_table('inventory_job_work_returns')
    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_item_id'))

    op.drop_table('inventory_job_work_receipts')
    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_item_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_issue_reference'))

    op.drop_table('inventory_job_work_issues')
    op.drop_table('inventory_goods_receipt_items')
    with op.batch_alter_table('inventory_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_exceptions_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_exceptions_sku_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_exceptions_exception_number'))

    op.drop_table('inventory_exceptions')
    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_balances_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_balances_sku_id'))

    op.drop_table('inventory_balances')
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_errors_import_record_id'))
        batch_op.drop_index(batch_op.f('ix_import_errors_import_job_id'))

    op.drop_table('import_errors')
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skus_sku_code'))
        batch_op.drop_index(batch_op.f('ix_skus_shopdeck_sku_id'))
        batch_op.drop_index(batch_op.f('ix_skus_item_code'))

    op.drop_table('skus')
    op.drop_table('product_attributes_link')
    with op.batch_alter_table('operations_tax_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_tax_invoices_order_id'))
        batch_op.drop_index(batch_op.f('ix_operations_tax_invoices_invoice_no'))

    op.drop_table('operations_tax_invoices')
    with op.batch_alter_table('operations_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_refunds_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_operations_refunds_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_operations_refunds_order_reference'))

    op.drop_table('operations_refunds')
    with op.batch_alter_table('operations_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_payments_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_operations_payments_settlement_id'))
        batch_op.drop_index(batch_op.f('ix_operations_payments_order_reference'))
        batch_op.drop_index(batch_op.f('ix_operations_payments_matched_order_id'))

    op.drop_table('operations_payments')
    with op.batch_alter_table('operations_order_state_transitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_order_state_transitions_order_id'))

    op.drop_table('operations_order_state_transitions')
    op.drop_table('import_summaries')
    with op.batch_alter_table('import_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_records_import_job_id'))

    op.drop_table('import_records')
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_files_md5_hash'))

    op.drop_table('import_files')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_product_code'))

    op.drop_table('products')
    with op.batch_alter_table('operations_sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_sales_orders_external_order_id'))

    op.drop_table('operations_sales_orders')
    with op.batch_alter_table('matching_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_relationships_target_type'))
        batch_op.drop_index(batch_op.f('ix_matching_relationships_target_id'))
        batch_op.drop_index(batch_op.f('ix_matching_relationships_source_type'))
        batch_op.drop_index(batch_op.f('ix_matching_relationships_source_id'))
        batch_op.drop_index(batch_op.f('ix_matching_relationships_relationship_type'))
        batch_op.drop_index(batch_op.f('ix_matching_relationships_match_job_id'))

    op.drop_table('matching_relationships')
    with op.batch_alter_table('matching_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_exceptions_match_job_id'))
        batch_op.drop_index(batch_op.f('ix_matching_exceptions_document_type'))
        batch_op.drop_index(batch_op.f('ix_matching_exceptions_document_id'))

    op.drop_table('matching_exceptions')
    with op.batch_alter_table('jwa_job_worker_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwa_job_worker_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_jwa_job_worker_payments_job_worker_id'))

    op.drop_table('jwa_job_worker_payments')
    op.drop_table('inventory_purchase_returns')
    op.drop_table('inventory_goods_receipts')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_integration_id'))

    op.drop_table('import_jobs')
    op.drop_table('category_attributes')
    with op.batch_alter_table('accounting_journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_journal_lines_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_journal_lines_journal_id'))

    op.drop_table('accounting_journal_lines')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_warehouse_code'))

    op.drop_table('warehouses')
    with op.batch_alter_table('units_of_measure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_of_measure_unit_code'))

    op.drop_table('units_of_measure')
    with op.batch_alter_table('system_sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_sequences_sequence_name'))

    op.drop_table('system_sequences')
    with op.batch_alter_table('shopdeck_downloaded_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopdeck_downloaded_reports_sync_run_id'))
        batch_op.drop_index(batch_op.f('ix_shopdeck_downloaded_reports_checksum'))

    op.drop_table('shopdeck_downloaded_reports')
    with op.batch_alter_table('product_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_attributes_attribute_code'))

    op.drop_table('product_attributes')
    with op.batch_alter_table('packer_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packer_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_packer_events_event_id'))

    op.drop_table('packer_events')
    with op.batch_alter_table('operations_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_settlements_settlement_id'))

    op.drop_table('operations_settlements')
    op.drop_table('operations_return_policies')
    op.drop_table('matching_jobs')
    op.drop_table('masters_suppliers')
    with op.batch_alter_table('inventory_outbound_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_outbound_events_event_id'))

    op.drop_table('inventory_outbound_events')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_integration_code'))

    op.drop_table('integrations')
    with op.batch_alter_table('import_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_import_audit_logs_batch_id'))

    op.drop_table('import_audit_logs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_company_code'))

    op.drop_table('companies')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_category_code'))

    op.drop_table('categories')
    with op.batch_alter_table('accounting_ledgers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_ledgers_ledger_code'))

    op.drop_table('accounting_ledgers')
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_journal_entries_reference_id'))
        batch_op.drop_index(batch_op.f('ix_accounting_journal_entries_journal_number'))

    op.drop_table('accounting_journal_entries')
    # ### end Alembic commands ###
