"""add_index_to_matched_order_id

Revision ID: a7dd4c1026ff
Revises: 010_operations_and_matching
Create Date: 2026-08-05 21:02:21.644266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dd4c1026ff'
down_revision: Union[str, None] = '010_operations_and_matching'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopdeck_downloaded_reports',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sync_run_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopdeck_downloaded_reports_checksum'), 'shopdeck_downloaded_reports', ['checksum'], unique=False)
    op.create_index(op.f('ix_shopdeck_downloaded_reports_sync_run_id'), 'shopdeck_downloaded_reports', ['sync_run_id'], unique=False)
    op.create_index(op.f('ix_operations_payments_matched_order_id'), 'operations_payments', ['matched_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_payments_matched_order_id'), table_name='operations_payments')
    op.drop_index(op.f('ix_shopdeck_downloaded_reports_sync_run_id'), table_name='shopdeck_downloaded_reports')
    op.drop_index(op.f('ix_shopdeck_downloaded_reports_checksum'), table_name='shopdeck_downloaded_reports')
    op.drop_table('shopdeck_downloaded_reports')
    # ### end Alembic commands ###
