"""drop_job_work_orders

Revision ID: b1706d3c2716
Revises: 5593efb16e36
Create Date: 2026-08-11 16:25:27.393644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1706d3c2716'
down_revision: Union[str, None] = '5593efb16e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop child table columns/constraints first
    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.alter_column('job_worker_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_index('ix_inventory_job_work_issues_jwo_id')
        batch_op.create_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.drop_column('jwo_id')

    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.alter_column('job_worker_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_index('ix_inventory_job_work_receipts_jwo_id')
        batch_op.create_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'), ['job_worker_id'], unique=False)
        batch_op.drop_column('jwo_id')

    # Now drop the parent table
    with op.batch_alter_table('inventory_job_work_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_job_work_orders_job_worker_id')
        batch_op.drop_index('ix_inventory_job_work_orders_jwo_number')
        batch_op.drop_index('ix_inventory_job_work_orders_target_item_id')

    op.drop_table('inventory_job_work_orders')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwo_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_job_work_orders', ['jwo_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'))
        batch_op.create_index('ix_inventory_job_work_receipts_jwo_id', ['jwo_id'], unique=False)
        batch_op.alter_column('job_worker_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwo_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_job_work_orders', ['jwo_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'))
        batch_op.create_index('ix_inventory_job_work_issues_jwo_id', ['jwo_id'], unique=False)
        batch_op.alter_column('job_worker_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    op.create_table('inventory_job_work_orders',
    sa.Column('jwo_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('job_worker_id', sa.CHAR(length=32), nullable=False),
    sa.Column('target_item_id', sa.CHAR(length=32), nullable=False),
    sa.Column('target_quantity', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=False),
    sa.Column('updated_on', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['job_worker_id'], ['masters_suppliers.id'], ),
    sa.ForeignKeyConstraint(['target_item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_orders', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_job_work_orders_target_item_id', ['target_item_id'], unique=False)
        batch_op.create_index('ix_inventory_job_work_orders_jwo_number', ['jwo_number'], unique=1)
        batch_op.create_index('ix_inventory_job_work_orders_job_worker_id', ['job_worker_id'], unique=False)

    # ### end Alembic commands ###
