"""Add UOM relationships to Product and BOM

Revision ID: cbdf529beb38
Revises: b1706d3c2716
Create Date: 2026-08-11 19:44:04.699536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdf529beb38'
down_revision: Union[str, None] = 'b1706d3c2716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removing redundant drops that were already handled by previous migrations
    # op.drop_table('inventory_job_work_orders')
    # op.drop_table('_alembic_tmp_inventory_job_work_issues')
    # Removing redundant alterations on inventory_job_work_issues and receipts
    # as they were already handled by previous migration b1706d3c2716

    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uom_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_masters_bom_items_uom_id'), ['uom_id'], unique=False)
        batch_op.create_foreign_key('fk_masters_bom_items_uom_id_units_of_measure', 'units_of_measure', ['uom_id'], ['id'])
        batch_op.drop_column('unit_of_measure')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_uom_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.create_foreign_key('fk_products_base_uom_id_units_of_measure', 'units_of_measure', ['base_uom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='generic_status_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ACTIVE'"))
        batch_op.drop_column('base_uom_id')

    with op.batch_alter_table('masters_bom_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_of_measure', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_masters_bom_items_uom_id'))
        batch_op.drop_column('uom_id')

    with op.batch_alter_table('inventory_job_work_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwo_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_job_work_orders', ['jwo_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_receipts_job_worker_id'))
        batch_op.create_index('ix_inventory_job_work_receipts_jwo_id', ['jwo_id'], unique=False)
        batch_op.alter_column('job_worker_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('inventory_job_work_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwo_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory_job_work_orders', ['jwo_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_job_work_issues_job_worker_id'))
        batch_op.create_index('ix_inventory_job_work_issues_jwo_id', ['jwo_id'], unique=False)
        batch_op.alter_column('job_worker_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    op.create_table('_alembic_tmp_inventory_job_work_issues',
    sa.Column('issue_number', sa.VARCHAR(length=255), nullable=False),
    sa.Column('item_id', sa.CHAR(length=32), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=False),
    sa.Column('updated_on', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
    sa.Column('job_worker_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_job_work_orders',
    sa.Column('id', sa.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_job_work_orders', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_job_work_orders_target_item_id', ['id'], unique=False)
        batch_op.create_index('ix_inventory_job_work_orders_jwo_number', ['id'], unique=False)
        batch_op.create_index('ix_inventory_job_work_orders_job_worker_id', ['id'], unique=False)

    # ### end Alembic commands ###
