"""add is_job_worker to suppliers

Revision ID: e67afde9fc2e
Revises: 1e6415b836c5
Create Date: 2026-08-10 11:33:25.201197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67afde9fc2e'
down_revision: Union[str, None] = '1e6415b836c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters_suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_job_worker', sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('masters_suppliers', schema=None) as batch_op:
        batch_op.drop_column('is_job_worker')

    # ### end Alembic commands ###
