"""add_packer_events

Revision ID: f4eb68aad924
Revises: 85bbd97c3bd7
Create Date: 2026-08-16 22:58:21.190398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f4eb68aad924'
down_revision: Union[str, None] = '85bbd97c3bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'packer_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('event_id', sa.Uuid(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('order_id', sa.String(length=100), nullable=False),
        sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
        sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_on', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by', sa.Uuid(), nullable=True),
        sa.Column('updated_by', sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packer_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packer_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_packer_events_order_id'), ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packer_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packer_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_packer_events_event_id'))

    op.drop_table('packer_events')
    # ### end Alembic commands ###
