from typing import Dict, Any, Optional
from datetime import datetime
from uuid import UUID

from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, DateTime, JSON
from sqlalchemy.dialects.postgresql import JSONB

from src.foundation.database.models import BaseModel


class PackerEventModel(BaseModel):
    __tablename__ = "packer_events"

    # The immutable event ID generated by the Packer system (idempotency key)
    event_id: Mapped[UUID] = mapped_column(nullable=False, unique=True, index=True)
    
    # Event type (e.g. "PACKED", "RTO_RECEIVED", "RETURN_RECEIVED")
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    
    # Commercial order ID associated with this event
    order_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    
    # When the physical event actually occurred in the warehouse
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    
    # When this event was received by our API
    received_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    
    # Status of processing ("PROCESSED", "FAILED")
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="PROCESSED")
    
    # The full JSON payload received from the Packer system for audit purposes
    payload: Mapped[Dict[str, Any]] = mapped_column(JSON().with_variant(JSONB, "postgresql"), nullable=False)
