from enum import Enum

class MovementType(str, Enum):
    OPENING_STOCK = "OPENING_STOCK"
    PURCHASE = "PURCHASE"
    SALE = "SALE"
    RETURN = "RETURN"
    RTO_RETURN = "RTO_RETURN"
    CUSTOMER_RETURN = "CUSTOMER_RETURN"
    ADJUSTMENT = "ADJUSTMENT"
    QC_RELEASE = "QC_RELEASE"

class InventoryState(str, Enum):
    AVAILABLE = "AVAILABLE"
    UNDER_INSPECTION = "UNDER_INSPECTION"
    DAMAGED = "DAMAGED"
    LOST = "LOST"

class ExceptionSource(str, Enum):
    ACCOUNTING = "ACCOUNTING"
    MARKETPLACE = "MARKETPLACE"
    PHYSICAL = "PHYSICAL"
    ENGINE = "ENGINE"

class ExceptionStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"

class GoodsReceiptType(str, Enum):
    RAW_MATERIAL_RECEIPT = "RAW_MATERIAL_RECEIPT"
    PURCHASED_FINISHED_GOODS = "PURCHASED_FINISHED_GOODS"
    JOB_WORK_RECEIPT = "JOB_WORK_RECEIPT"

class TransformationReason(str, Enum):
    JOB_WORK = "JOB_WORK"
    MANUFACTURING = "MANUFACTURING"
    REPACKING = "REPACKING"
    KIT_ASSEMBLY = "KIT_ASSEMBLY"
    DISASSEMBLY = "DISASSEMBLY"
